package FMDE_End.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int A = 0;
  public static final int Edge = 1;
  public static final int EdgeMapping = 2;
  public static final int FinSet = 3;
  public static final int FinSetElement = 4;
  public static final int FinSets = 5;
  public static final int GraphMapping = 6;
  public static final int GraphSet = 7;
  public static final int GraphSets = 8;
  public static final int Graphfunction = 9;
  public static final int IDs_and_Compositions = 10;
  public static final int Mapping = 11;
  public static final int Node = 12;
  public static final int TotalFunction = 13;
  public static final int arrow = 14;
  public static final int composition = 15;
  public static final int id = 16;
  public static final int object = 17;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xd0a0492b832b46e1L, 0x9328665a3140e72eL);
    builder.put(0x7d77430a19606190L, A);
    builder.put(0x6058905b743a5893L, Edge);
    builder.put(0x6058905b743b7363L, EdgeMapping);
    builder.put(0x322424eea67db0e8L, FinSet);
    builder.put(0x322424eea67e5521L, FinSetElement);
    builder.put(0x322424eea67db0e7L, FinSets);
    builder.put(0x6058905b743a5897L, GraphMapping);
    builder.put(0x322424eea67db103L, GraphSet);
    builder.put(0x6058905b743a201cL, GraphSets);
    builder.put(0x322424eea67db104L, Graphfunction);
    builder.put(0x2b06f517158b15a0L, IDs_and_Compositions);
    builder.put(0x6058905b74386cf7L, Mapping);
    builder.put(0x6058905b743a588fL, Node);
    builder.put(0x322424eea67db0e9L, TotalFunction);
    builder.put(0x322424eea67db0e4L, arrow);
    builder.put(0x322424eea67db0e5L, composition);
    builder.put(0x322424eea67db0e6L, id);
    builder.put(0x322424eea67db0e3L, object);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
